# Generated by Django 3.2.9 on 2021-11-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211125_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_background',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
