# Generated by Django 3.2.9 on 2021-11-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(max_length=255)),
                ('language', models.CharField(choices=[('TXT', 'Plain Text'), ('JS', 'JavaScript'), ('PY', 'Python'), ('TS', 'TypeScript'), ('PHP', 'PHP'), ('CSS', 'CSS')], default='TXT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('cover_img', models.URLField(null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('featured_code', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='technologies.featuredcode')),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('url', models.URLField()),
                ('is_free', models.BooleanField(default=True)),
                ('technologies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='technologies.technology')),
            ],
        ),
    ]
