# Generated by Django 3.2.9 on 2021-11-05 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='technologies',
            new_name='technology',
        ),
    ]
