# Generated by Django 3.2.9 on 2021-11-06 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_rename_technologies_resource_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='featured_code',
        ),
        migrations.AddField(
            model_name='featuredcode',
            name='technology',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='technologies.technology'),
            preserve_default=False,
        ),
    ]
