# Generated by Django 3.2.9 on 2021-11-06 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0004_auto_20211106_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='featured_code',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='technologies.featuredcode'),
        ),
    ]
