# Generated by Django 3.2.9 on 2021-11-14 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0005_alter_technology_featured_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='featured_code',
        ),
        migrations.AddField(
            model_name='featuredcode',
            name='technology',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='technologies.technology'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resource',
            name='technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='technologies.technology'),
        ),
    ]
