# Generated by Django 3.2.9 on 2021-11-14 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0006_auto_20211114_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcode',
            name='technology',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured_code', to='technologies.technology'),
        ),
    ]
